#file: noinspection SpringBootApplicationYaml
server:
  port: 8095

spring:
  security:
    enabled: false

  application:
    name: api-gateway

  config:
    import: "file:./env.properties"

  r2dbc:
    url: ${DB_POSTGRES_REACTIVE_URL}
    username: ${DB_POSTGRES_USERNAME}
    password: ${DB_POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: trainees
          uri: lb://GYM-APP
          predicates:
            - Path=/api/v1/trainees/**
          filters:
            - name: JwtAuthentication
              args:
                allowedRoles:
                  - ROLE_TRAINEE

        - id: trainers
          uri: lb://GYM-APP
          predicates:
            - Path=/api/v1/trainers/**
          filters:
            - name: JwtAuthentication
              args:
                allowedRoles:
                  - ROLE_TRAINER

        - id: trainings
          uri: lb://GYM-APP
          predicates:
            - Path=/api/v1/trainings/**
          filters:
            - name: JwtAuthentication
              args:
                allowedRoles:
                  - ROLE_TRAINEE
                  - ROLE_TRAINER

        - id: training-report
          uri: lb://TRAINING-REPORT
          predicates:
            - Path=/api/v1/workload/**
          filters:
            - name: JwtAuthentication
              args:
                allowedRoles:
                  - ROLE_TRAINEE
                  - ROLE_TRAINER

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    issuer: GymApp
    expiration-ms: 3600000  # 1 hour
    refresh-token-expiration-ms: 604800000  # 7 days