server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: none

  profiles:
    active: dev

logging:
  level:
    root: WARN

management:
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

security:
  jwt:
    secret-key: my-32-character-ultra-secure-and-ultra-long-secret
    issuer: Atabek