spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_app
    username: postgres
    password: 91926499
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public

  flyway:
    schemas: public
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
    default-schema: public
    baseline-version: 11

logging:
  level:
    root: ERROR

management:
  endpoints:
    web:
      exposure:
        include: 'health'