spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_app
    username: postgres
    password: 91926499
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: stage

  flyway:
    schemas: stage
    default-schema: stage
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: false
    clean-disabled: true
    baseline-version: 11

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'
