server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: WARN
    sun.rmi.transport.tcp: WARN
    sun.rmi.server: ERROR
    sun.rmi.registry: ERROR
    sun.rmi.loader: WARN
    javax.management.remote.rmi: WARN