server:
  port: 0

spring:
  datasource:
    url: ${DB_H2_TRAINING_URL}
    driver-class-name: org.h2.Driver
    username: ${DB_H2_TRAINING_USERNAME}
    password: ${DB_H2_TRAINING_PASSWORD}

  cloud:
    config:
      fail-fast: true

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  activemq:
    broker-url: tcp://localhost:61616 # External ActiveMQ broker
    user: admin                      # ActiveMQ username
    password: admin                  # ActiveMQ password
    packages:
      trust-all: true                # Trust all packages for serialization

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
    hostname: localhost

management:
  endpoints:
    web.exposure:
      include: info,health # And any other endpoints you wish to expose
  tracing:
    enabled: true
    sampling:
      probability: 1.0