spring:
  datasource:
    url: ${DB_POSTGRES_URL}
    username: ${DB_POSTGRES_USERNAME}
    password: ${DB_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: stage

  flyway:
    schemas: stage
    default-schema: stage
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: false
    clean-disabled: true
    baseline-version: 11

logging:
  level:
    root: WARN

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'
