server:
  port: ${GYM_APP_PORT:0}

spring:
  application:
    name: gym-app

  jpa:
    hibernate:
      ddl-auto: none

  devtools:
    restart:
      enabled: false

  main:
    allow-bean-definition-overriding: true

  config:
    import: "optional:file:./env.properties"

  profiles:
    active: prod

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost

logging:
  level:
    root: WARN
    sun.rmi.transport.tcp: WARN
    sun.rmi.server: ERROR
    sun.rmi.registry: ERROR
    sun.rmi.loader: WARN
    javax.management.remote.rmi: WARN

management:
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      trainingReportClient:
        baseConfig: default