spring:
  application:
    name: gym-app

  profiles:
    active: default

  config:
    import:
      - optional:configserver:http://localhost:8888
      - file:../env.properties

  cloud:
    config:
      fail-fast: true